// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// import Providers from "@/provider/index";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <Providers>
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           {children}
//         </body>
//       </Providers>
//       {/* เอา Providers มาครอบไว้งี้ มันก็ไปเรียก theme ของ MUI CssBaseline มาใช้ได้ละ */}
//     </html>
//   );
// }

import type { Metadata, Viewport } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'NIDA Learning Platform',
  description: 'Nida environment school',
  icons: {
    apple: '/apple-touch-icon.png',
    icon: ['/icon.png'],
    shortcut: '/icon.png',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
